# inspired from https://github.com/imaya/zlib.js THANKS!

before_install:
  - sudo apt-get update && sudo apt-get install gconf2
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./.travis/scripts/install_chrome.sh

before_script:
  - node_modules/.bin/buster-server &
  - sleep 5
  - .travis/firefox-start.sh http://localhost:1111/capture &
  - sleep 5
  - .travis/chrome-start.sh http://localhost:1111/capture &
  - sleep 5
#  - phantomjs node_modules/buster/script/phantom.js http://localhost:1111/capture &
# - sleep 5

install:
  - "ant"
  - "npm install"

script:
  - "npm test"

language: node_js

node_js:
  - 0.8
